name: Test Docker Hub Images

on: 
  schedule:
    # Run once a week at midnight on Sunday morning
    - cron '0 0 * * 0'
  
jobs:
  centos7-17.5.0:
    runs-on: ubuntu-18.04
    container: docker://nasatrick/trick_centos7:17.5.0
    steps:
      - name: run tests
        run: |
          cd /trick-17.5.0
          make test
