name: Trick CI

on: [push]

jobs:
  ubuntu-1804:
    runs-on: ubuntu-18.04
    container: docker://ubuntu:18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y git bison curl flex g++ libx11-dev libxml2-dev libxt-dev libmotif-common libmotif-dev make openjdk-8-jdk python2.7-dev swig zlib1g-dev llvm llvm-dev clang libclang-dev libudunits2-dev libgtest-dev cmake
    - name: Build gtest
      run: cd /usr/src/gtest && cmake . && make && cp libgtest* /usr/lib/

    - name: Build Trick
      run: |
        export MAKEFLAGS=-j2
        ./configure
        make
    - name: Run tests
      run: make test
  
  fedora-30:
    runs-on: ubuntu-18.04
    container: docker://fedora:30
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Install dependencies
      run: |
        dnf install -y git bison flex gcc gcc-c++ libxml2-devel make openmotif openmotif-devel python-devel perl swig zlib-devel llvm llvm-devel llvm-static clang clang-devel perl-Text-Balanced perl-Digest-MD5 udunits2 udunits2-devel java-1.8.0-openjdk-devel ncurses-devel which
    - name: Install gtest
      run:  dnf install -y gtest-devel

    - name: Build Trick
      run: |
        export MAKEFLAGS=-j2
        ./configure
        make
    - name: Run tests
      run: make test
  test-dockerhub-centos7:
    runs-on: ubuntu-18.04
    container: docker://nasatrick/trick_centos7:17.5.0
    steps:
      - name: run tests
        run |
          cd /trick-17.5.0
          make test -j2
          
