name: TrickOps
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  unit-tests-ubuntu:
    name: Unit Tests Ubuntu:20.04
    runs-on: ubuntu-20.04
    container: ubuntu:20.04
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        # Note that perl is for trick-gte which TrickOps runs and qt and everything after it is for koviz
        run: |
          export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y python3 python3-venv perl perl-modules-5.30 qtbase5-dev wget unzip g++ make flex bison
      - name: create virtual environment
        run: |
          cd share/trick/trickops/
          python3 -m venv .venv && source .venv/bin/activate && pip3 install -r requirements.txt
      - name: get and build koviz
        run: |
          cd /tmp/ && wget -q https://github.com/nasa/koviz/archive/refs/heads/master.zip && unzip master.zip
          cd /tmp/koviz-master/ &&  qmake && make
      - name: run unit and doc tests
        run: |
          cd share/trick/trickops/tests/
          source ../.venv/bin/activate
          export PATH="/tmp/koviz-master/bin:${PATH}"
          ./run_tests.py
      - uses: actions/upload-artifact@master
        if: ${{ always() }}
        with:
          name: doctests
          path: |
            share/trick/trickops/tests/*_doctest_log.txt
            /tmp/log.*

  unit-tests-centos8:
    name: Unit Tests CentOS:latest
    runs-on: ubuntu-20.04
    container: centos:latest
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        # Note that perl is for trick-gte which TrickOps runs and qt and everything after it is for koviz
        run: |
          dnf install -y python3-devel which perl perl-Digest-MD5 qt5-qtbase-devel bison clang flex make gcc gcc-c++ wget
      - name: create virtual environment
        run: |
          cd share/trick/trickops/
          python3 -m venv .venv && source .venv/bin/activate && pip3 install -r requirements.txt
      - name: get and build koviz
        run: |
          cd /tmp/ && wget -q https://github.com/nasa/koviz/archive/refs/heads/master.zip && unzip master.zip
          cd /tmp/koviz-master/ &&  qmake-qt5 && make
      - name: run unit and doc tests
        run: |
          cd share/trick/trickops/tests/
          source ../.venv/bin/activate
          export PATH="/tmp/koviz-master/bin:${PATH}"
          ./run_tests.py
      - uses: actions/upload-artifact@master
        if: ${{ always() }}
        with:
          name: doctests
          path: |
            share/trick/trickops/tests/*_doctest_log.txt
            /tmp/log.*
